name = "mari0_aces"
default_targets = ["win32", "win64", "macos"]
icon_file = "graphics/icon.png"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

[archive_files]
"README.md" = "README.md"
"LICENSE.txt" = "LICENSE.txt"

[windows.exe_metadata]
ProductName = "Mari0: ACES"
CompanyName = "KirbyKidJ"
LegalCopyright = "Copyright © 2006-2024 Maurice Guégan"

[linux.desktop_file_metadata]
Name = "Mari0: ACES"

[macos.app_metadata]
CFBundleDisplayName = "Mari0: ACES"
CFBundleIdentifier = "com.kirbykidj"
NSHumanReadableCopyright = "Copyright © 2006-2024 Maurice Guégan"
